version: "3.7"

x-service-base: &service
  logging:
    driver: "fluentd"
    options:
      fluentd-address: localhost:24224
  # https://docs.docker.com/compose/compose-file/#restart
  restart: ${DOCKER_RESTART:-unless-stopped}

# https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html#docker-compose-file
x-elastic-base: &elastic_base
  image: ${ELASTIC_REGISTRY}/elasticsearch/elasticsearch:${ELASTIC_VERSION}
  ulimits:
    memlock:
      soft: -1
      hard: -1
    #---
  logging:
    driver: "json-file" # TODO: fluentd
    options:
      max-size: "3m"
      max-file: "1"
  # https://docs.docker.com/compose/compose-file/#restart
  restart: ${DOCKER_RESTART:-unless-stopped}

x-elastic-env: &elastic_env
  cluster.name: es-docker-cluster
  bootstrap.memory_lock: "true"
  ES_JAVA_OPTS: "-Xms512m -Xmx512m"

services:
  #--- es single node
  elasticsearch:
    <<: *elastic_base
    environment:
      <<: *elastic_env
      discovery.type: single-node
    volumes:
      - es-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

  #--- kibana
  kibana:
    image: ${ELASTIC_REGISTRY}/kibana/kibana:${ELASTIC_VERSION}
    # volumes:
    #   - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
    #environment: # https://www.elastic.co/guide/en/kibana/current/docker.html#docker-defaults
    #ELASTICSEARCH_HOSTS: http://elasticsearch.example.org
    ports:
      - 5601:5601

  #--- fluentd
  # - https://docs.fluentd.org/container-deployment/docker-compose
  fluentd: # https://hub.docker.com/r/fluent/fluentd
    image: fluent/fluentd-kubernetes-daemonset:${FLUENTD_VERSION}
    ports:
      - 24224:24224
      - 24224:24224/udp
    volumes:
      - ./fluentd/conf/:/fluentd/etc/

  #--- es 3-node cluster -------------------------
  es01:
    <<: *elastic_base
    container_name: es01
    environment:
      <<: *elastic_env
      node.name: es01
      cluster.initial_master_nodes: es01,es02,es03
      discovery.seed_hosts: es02,es03
    volumes:
      - es-data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
  es02:
    <<: *elastic_base
    container_name: es02
    environment:
      <<: *elastic_env
      node.name: es02
      cluster.initial_master_nodes: es01,es02,es03
      discovery.seed_hosts: es01,es03
    volumes:
      - es-data02:/usr/share/elasticsearch/data
  es03:
    <<: *elastic_base
    container_name: es03
    environment:
      <<: *elastic_env
      node.name: es03
      cluster.initial_master_nodes: es01,es02,es03
      discovery.seed_hosts: es01,es02
    volumes:
      - es-data03:/usr/share/elasticsearch/data

volumes:
  es-data:
    driver: local
  es-data01:
    driver: local
  es-data02:
    driver: local
  es-data03:
    driver: local
